%% Diagramme des cas d'utilisation (Mermaid)
```mermaid
flowchart TB
  actor(Utilisateur)
  system(Bibliothèque)
  Utilisateur -->|Consulter catalogues| Bibliothèque
  Utilisateur -->|S'inscrire| Bibliothèque
  Utilisateur -->|Emprunter livre| Bibliothèque
  Utilisateur -->|Retourner livre| Bibliothèque
  Utilisateur -->|Réserver livre| Bibliothèque
```
